
title: "Henry Nguyễn"
name: "Henry Nguyễn"
avatar: "/assets/img/avatar.jpg"
description: "Xin chào! Mình là Henry Nguyễn, đam mê công nghệ và sáng tạo nội dung."
url: "https://longne1808.github.io"
github_username: Longne1808

social:
  facebook: "https://www.facebook.com/filong1808"
